// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/pdh9523/go-hexarch/applications/rest-server/container"
	"github.com/pdh9523/go-hexarch/domains/user/application/service"
	adapter2 "github.com/pdh9523/go-hexarch/infrastructure/cache-redis/adapter"
	config3 "github.com/pdh9523/go-hexarch/infrastructure/cache-redis/config"
	"github.com/pdh9523/go-hexarch/infrastructure/gorm/adapter"
	config2 "github.com/pdh9523/go-hexarch/infrastructure/gorm/config"
	"github.com/pdh9523/go-hexarch/presentation/rest/handler/user"
	"github.com/pdh9523/go-hexarch/shared/security"
	"github.com/pdh9523/go-hexarch/shared/security/config"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// NewContainer creates a new application container with all dependencies
func NewContainer() (container.Container, error) {
	configConfig := config.DefaultConfig()
	manager := security.NewManager(configConfig)
	gormConfig := config2.NewGormConfig()
	db, err := ProvideGormDB(gormConfig)
	if err != nil {
		return nil, err
	}
	userRepositoryPort := adapter.NewUserRepositoryAdapter(db)
	redisConfig := config3.NewRedisConfig()
	redisClient, err := config3.NewRedisClient(redisConfig)
	if err != nil {
		return nil, err
	}
	userCachePort := adapter2.NewUserCacheAdapter(redisClient)
	userUseCase := service.NewUserService(manager, userRepositoryPort, userCachePort)
	userHandler := handler.NewUserHandler(userUseCase)
	containerContainer := ProvideContainer(userHandler)
	return containerContainer, nil
}

// wire.go:

// DatabaseSet provides database-related dependencies
var DatabaseSet = wire.NewSet(config2.NewGormConfig, ProvideGormDB, adapter.NewUserRepositoryAdapter)

// CacheSet provides cache-related dependencies
var CacheSet = wire.NewSet(config3.NewRedisConfig, config3.NewRedisClient, adapter2.NewUserCacheAdapter)

// SecuritySet provides security-related dependencies
var SecuritySet = wire.NewSet(config.DefaultConfig, security.NewManager)

// ApplicationSet provides application service dependencies
var ApplicationSet = wire.NewSet(service.NewUserService)

// PresentationSet provides presentation layer dependencies
var PresentationSet = wire.NewSet(handler.NewUserHandler)

// ProvideContainer creates a container implementation
func ProvideContainer(userHandler *handler.UserHandler) container.Container {
	return &containerImpl{
		userHandler: userHandler,
	}
}

// containerImpl implements the Container interface
type containerImpl struct {
	userHandler *handler.UserHandler
}

func (c *containerImpl) UserHandler() *handler.UserHandler {
	return c.userHandler
}

// ProvideGormDB is a wrapper for GormConfig.NewGormDB method
func ProvideGormDB(config4 *config2.GormConfig) (*gorm.DB, error) {
	return config4.NewGormDB()
}
